export const ENTITLEMENT_TIMEZONE = "Asia/Kolkata";

export const ENTITLEMENT_LIMITS = {
  GUEST_AI_TRIAL_SECONDS: 120,
  FREE_AI_DAILY_SECONDS: 120,
  FREE_AI_MONTHLY_SECONDS: 600,
  FREE_PEER_DAILY_SECONDS: 300,
  PREMIUM_AI_MONTHLY_SECONDS: 3600,
  PREMIUM_PEER_DAILY_SECONDS: 1800,
  VOICE_SESSION_MAX_SECONDS: 300,
} as const;

export type EntitlementLimits = typeof ENTITLEMENT_LIMITS;
